# Generated by Django 5.1.3 on 2024-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_payment_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("наличные", "наличные"),
                    ("перевод на счет", "перевод на счет"),
                ],
                max_length=50,
                null=True,
                verbose_name="Cпособ оплаты",
            ),
        ),
    ]
